shared:
  default_gaiad_host: <%= ENV['GAIAD_HOST'].present? ? ENV['GAIAD_HOST'] : 'localhost' %>
  default_rpc_port: 26657
  default_lcd_port: 1317
  database: {}

development:
  application_host: localhost:3000
  application_protocol: http

staging:
  application_host: staging.secret.foundation
  application_protocol: https

production:
  application_host: secret.foundation
  application_protocol: https
