shared:
  default_gaiad_host: <%= ENV['GAIAD_HOST'].present? ? ENV['GAIAD_HOST'] : 'localhost' %>
  default_rpc_port: 26657
  default_lcd_port: 1317
  database: {}
  rollbar_token: YOUR_ROLLBAR_TOKEN
  recaptcha:
    site: RECAPTCHA_SITE
    secret: RECAPTCHA_SECRET

development:
  application_host: localhost:3000
  application_protocol: http
  secret_key_base: DEV_SKB
  faucet_key_base: DEV_FKB

staging:
  application_host: staging-puzzle.secretnodes.org
  application_protocol: https
  postmark: STAGING_POSTMARK
  secret_key_base: STAGING_SKB
  faucet_key_base: STAGING_FBK
  http_basic_password: PASSWORD
  database:
    password: STAGING_DB_PASS
    host: STAGING_DB_HOST
    user: STAGING_DB_USER

production:
  application_host: puzzle.secretnodes.org
  application_protocol: https
  postmark: "9016f7a5-65dc-488d-980d-e98930c7e90b"
  secret_key_base: PRODUCTION_SKB
  faucet_key_base: PRODUCTION_FKB
  database:
    password: PRODUCTION_DB_PASS
    host: PRODUCTION_DB_HOST
    user: PRODUCTION_DB_USER
